name: NormalizInterface
version: "1.3.7"
license: "GPL-2.0-or-later"
date: 2024-07-07
description: |
    GAP wrapper for Normaliz

authors:
    - name: Sebastian Gutsche
      url: mailto:gutsche@mathematik.uni-siegen.de
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christof Söger
      url: mailto:csoeger@uos.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.12.1"

www: https://gap-packages.github.io/NormalizInterface
readme: README.md
packageinfo: https://gap-packages.github.io/NormalizInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v1.3.7/NormalizInterface-1.3.7.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v1.3.7/NormalizInterface-1.3.7.tar.bz2

abstract: |
    The <span class='pkgname'>NormalizInterface</span> package provides  a GAP interface to <a href='https://www.normaliz.uni-osnabrueck.de'>Normaliz</a>,  enabling direct access to the complete functionality of Normaliz, such as  computations in affine monoids, vector configurations, lattice polytopes, and rational cones.  

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    normaliz, cones.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GHS24</span>]   <b class='BibAuthor'>Gutsche, S., Horn, M. and Söger, C.</b>,
     <i class='BibTitle'>NormalizInterface, GAP wrapper for Normaliz,
             Version 1.3.7</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/NormalizInterface">https://gap-packages.github.io/NormalizInterface</a></span>.
    </p>
    

bibtex: |
    @misc{ NormalizInterface,
      author =           {Gutsche, S. and Horn, M. and S{\"o}ger, C.},
      title =            {{NormalizInterface},   GAP   wrapper   for   Normaliz,
                          {V}ersion 1.3.7},
      month =            {Jul},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/NormalizInterface}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{NormalizInterface}}},
      keywords =         {normaliz; cones},
      printedkey =       {GHS24}
    }

