name: NormalizInterface
version: 1.1.0
date: 2019-08-23
description: |
    GAP wrapper for Normaliz

authors:
    - name: Sebastian Gutsche
      url: https://algebra.mathematik.uni-siegen.de/gutsche/
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christof Söger
      url: https://www.normaliz.uni-osnabrueck.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

www: https://gap-packages.github.io/NormalizInterface
readme: README.md
packageinfo: https://gap-packages.github.io/NormalizInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v1.1.0/NormalizInterface-1.1.0.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v1.1.0/NormalizInterface-1.1.0.tar.bz2

abstract: |
    The <span class='pkgname'>NormalizInterface</span> package provides  a GAP interface to <a href='https://www.normaliz.uni-osnabrueck.de'>Normaliz</a>,  enabling direct access to the complete functionality of Normaliz, such as  computations in affine monoids, vector configurations, lattice polytopes, and rational cones.  

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
