## This is an automatically generated file

#! @Chapter Functions
#! @Section Cone properties

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "AffineDim" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzAffineDim" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ClassGroup" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzClassGroup" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Deg1Elements" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzDeg1Elements" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Dehomogenization" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzDehomogenization" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ExcludedFaces" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzExcludedFaces" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ExtremeRays" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzExtremeRays" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Generators" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzGenerators" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Grading" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzGrading" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "HilbertBasis" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzHilbertBasis" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "HilbertQuasiPolynomial" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzHilbertQuasiPolynomial" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "HilbertSeries" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzHilbertSeries" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "InclusionExclusionData" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzInclusionExclusionData" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "IsDeg1ExtremeRays" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzIsDeg1ExtremeRays" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "IsDeg1HilbertBasis" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzIsDeg1HilbertBasis" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "IsIntegrallyClosed" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzIsIntegrallyClosed" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "IsPointed" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzIsPointed" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ModuleGenerators" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzModuleGenerators" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ModuleGeneratorsOverOriginalMonoid" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzModuleGeneratorsOverOriginalMonoid" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ModuleRank" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzModuleRank" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Multiplicity" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzMultiplicity" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "OriginalMonoidGenerators" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzOriginalMonoidGenerators" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "RecessionRank" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzRecessionRank" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "IsReesPrimary" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzIsReesPrimary" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "ReesPrimaryMultiplicity" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzReesPrimaryMultiplicity" );

#! @Arguments cone
#! @Returns the equations
#! @Description
#! The equations cut out the linear space generated by the cone.
#! Together with the support hyperplanes and the congruences it describes the
#! lattice points of the cone.
#!  This is an alias for <C>NmzConeProperty( cone, "SupportHyperplanes" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzSupportHyperplanes" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "Triangulation" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzTriangulation" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "TriangulationDetSum" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzTriangulationDetSum" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "TriangulationSize" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzTriangulationSize" );

#! @Arguments cone
#! @Description
#!  This is an alias for <C>NmzConeProperty( cone, "VerticesOfPolyhedron" );</C> see <Ref Func="NmzConeProperty"/>
DeclareGlobalFunction( "NmzVerticesOfPolyhedron" );

