name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
      - main
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the default repository branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name != github.event.repository.default_branch || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-version }} ${{ matrix.os }}${{ matrix.system-libnormaliz && ' libnormaliz' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - 'devel'
          - '4.15'
          - '4.14'
          - '4.13'
          - '4.12'
        os: [ubuntu-latest]
        system-libnormaliz: [true,false]
        include:
          - gap-version: 'devel'
            os: macos-latest
            system-libnormaliz: false

    steps:
      - uses: actions/checkout@v6
      - name: "Install and use system libnormaliz"
        if: ${{ matrix.system-libnormaliz }}
        run: |
          rm prerequisites.sh   # prevent build-pkg from building Normaliz
          sudo apt install libnormaliz-dev   # install system libnormaliz
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v3
      - uses: gap-actions/run-pkg-tests@v4
      - uses: gap-actions/run-pkg-tests@v4
        with:
          mode: onlyneeded
      - uses: gap-actions/process-coverage@v3
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

#   test-cygwin:
#     name: "cygwin64 - GAP master"
#     runs-on: windows-latest
#     env:
#       CHERE_INVOKING: 1
#     steps:
#       - uses: actions/checkout@v6
#       - uses: gap-actions/setup-cygwin@v1
#       - uses: gap-actions/setup-gap@cygwin-v2
#         with:
#           GAP_PKGS_TO_BUILD: "normalizinterface profiling io"
#       - uses: gap-actions/build-pkg@cygwin-v1
#       - uses: gap-actions/run-pkg-tests@cygwin-v2
#       - uses: gap-actions/process-coverage@cygwin-v2
#       - uses: codecov/codecov-action@v6
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
#       - name: "Setup tmate session"
#         uses: mxschmitt/action-tmate@v3
#         if: ${{ failure() }}
#         timeout-minutes: 15
