name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.12
          - stable-4.11
          - stable-4.10
          - stable-4.9
        os: [ubuntu-latest]
        include:
          - gap-branch: master
            os: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v3

  test-cygwin:
    name: "cygwin64 - GAP master"
    runs-on: windows-latest
    env:
      CHERE_INVOKING: 1
    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-cygwin@v1
      - uses: gap-actions/setup-gap@cygwin-v2
        with:
          GAP_PKGS_TO_BUILD: "normalizinterface profiling io"
      - uses: gap-actions/build-pkg@cygwin-v1
      - uses: gap-actions/run-pkg-tests@cygwin-v2
      - uses: gap-actions/process-coverage@cygwin-v2
      - uses: codecov/codecov-action@v3
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v3
        with:
          name: manual
          path: ./doc/manual.pdf
